### ISSUE TITLE
Steps for converting to Python 3

### ISSUE THREAD

**Issue by yashkotadia** [uvavision/Balanced-Datasets-Are-Not-Enough#1]
Hey,
I am trying to run your code using Python 3 and have obviously run into errors.

Could you please outline the correct steps that would be required to run this repo with python 3.

For your reference, this is the error I run into: 
CUDA_VISIBLE_DEVICES=1 python dataset_leakage.py --num_epochs 100 --learning_rate 0.00005 --batch_size 16 --num_rounds 5 --no_image
Traceback (most recent call last):
  File "dataset_leakage.py", line 26, in <module>
    from data_loader import CocoObjectGender
  File "/home/yash/Documents/Balanced-Datasets-Are-Not-Enough/object_multilabel/data_loader.py", line 7, in <module>
    from pycocotools.coco import COCO
  File "/home/yash/Documents/Balanced-Datasets-Are-Not-Enough/object_multilabel/pycocotools/coco.py", line 55, in <module>
    from . import mask as maskUtils
  File "/home/yash/Documents/Balanced-Datasets-Are-Not-Enough/object_multilabel/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
ImportError: No module named 'pycocotools._mask'

**Comment by tianlu-wang** [comment]
This is not an issue caused by Python3. You need to download cocoapi repo, compile it and replace the pycocotools. https://github.com/cocodataset/cocoapi/issues/14

**Comment by yashkotadia** [comment]
I understand. Thank you
