### ISSUE TITLE
Bug in running adv_attacker.py on imSitu dataset

### ISSUE THREAD

**Issue by AiliAili** [uvavision/Balanced-Datasets-Are-Not-Enough#5]
Hi there,

Thank you for sharing your great work.

When running adv_attacker.py on the imSitu dataset, we encountered the following errors (we are referring to Balanced-Datasets-Are-Not-Enough/blob/master/verb_classification/commands.ipynb "python adv_attacker.py --exp_id conv5_300_1.0_0.2_imSitu_linear_0 --adv_on --layer conv5 --no_avgpool --adv_capacity 300 --adv_lambda 1 --learning_rate 0.00005 --num_epochs 100 --batch_size 128").

```
Traceback (most recent call last):
  File "adv_attacker.py", line 384, in <module>
    main()
  File "adv_attacker.py", line 298, in main
    model_save_dir, feature_type)
  File "adv_attacker.py", line 327, in train_attacker
    loss, train_task_acc = epoch_pass(epoch, train_loader, attacker, encoder, optimizer, True, feature_type, print_every)
  File "adv_attacker.py", line 364, in epoch_pass
    adv_pred = attacker(features)
  File "/usr/local/easybuild-2019/easybuild/software/mpi/gcc-cuda/8.3.0-10.1.243/openmpi/3.1.4/pytorch/1.4.0-python-3.7.4/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/gpfs/projects/punim1421/Balanced-Datasets-Are-Not-Enough/verb_classification/adv/adv_model.py", line 232, in forward
    return self.mlp(input_rep)
  File "/usr/local/easybuild-2019/easybuild/software/mpi/gcc-cuda/8.3.0-10.1.243/openmpi/3.1.4/pytorch/1.4.0-python-3.7.4/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/easybuild-2019/easybuild/software/mpi/gcc-cuda/8.3.0-10.1.243/openmpi/3.1.4/pytorch/1.4.0-python-3.7.4/lib/python3.7/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/usr/local/easybuild-2019/easybuild/software/mpi/gcc-cuda/8.3.0-10.1.243/openmpi/3.1.4/pytorch/1.4.0-python-3.7.4/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/easybuild-2019/easybuild/software/mpi/gcc-cuda/8.3.0-10.1.243/openmpi/3.1.4/pytorch/1.4.0-python-3.7.4/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 107, in forward
    exponential_average_factor, self.eps)
  File "/usr/local/easybuild-2019/easybuild/software/mpi/gcc-cuda/8.3.0-10.1.243/openmpi/3.1.4/pytorch/1.4.0-python-3.7.4/lib/python3.7/site-packages/torch/nn/functional.py", line 1670, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: running_mean should contain 2 elements not 211
```
Could you please help us?

Also, could you please share your hyperparameters with us in running adv_train.py?

Thank you very much.

Cheers,

**Comment by tianlu-wang** [comment]
Hi, I believe this is caused by a different version of PyTorch.

The command to run adv_train.py and ae_adv_train.py might be:

CUDA_VISIBLE_DEVICES=4 python train.py --exp_id imSitu_linear_0 --layer conv5 --adv_capacity 300 --adv_lambda 0.5 --dropout 0.2 --batch_size 32 --num_epochs 150 --batch_balanced --learning_rate 0.00001 --no_avgpool --resume --finetune --adv_on

CUDA_VISIBLE_DEVICES=4 python ae_adv_attacker.py --exp_id generated_image_10.0_1.0_0 --adv_on --layer generated_image --gender_balanced --adv_lambda 10 --batch_size 16 --latest_model


Although I am not 100% sure :( I will let you know if I find the exact command.

**Comment by AiliAili** [comment]
Thank you for your reply.

Do you think there is a chance that the code mixes up the number of verb classes with the number of gender classes (as the number of classes for imSitu is 211 and the number of gender classes is 2)?

When I run the corresponding scripts for MSCOCO, there is no issues occurred.

Cheers,

**Comment by HanXudong** [comment]
Hi Tianlu and Aili,

The ```potentials``` are stored as the input of the attacker to estimate the leakage,
https://github.com/uvavision/Balanced-Datasets-Are-Not-Enough/blob/51d66c54a81ad88a3ffd6a15d3807be3d5263f01/verb_classification/adv/adv_attacker.py#L32-L41

and the ```generate_image_feature``` is called as follows where the ```adv_model``` is used as the encoder.
https://github.com/uvavision/Balanced-Datasets-Are-Not-Enough/blob/51d66c54a81ad88a3ffd6a15d3807be3d5263f01/verb_classification/adv/adv_attacker.py#L262-L265

The ```adv_model``` is initialled as 
https://github.com/uvavision/Balanced-Datasets-Are-Not-Enough/blob/51d66c54a81ad88a3ffd6a15d3807be3d5263f01/verb_classification/adv/adv_attacker.py#L204

Here is the model structure of the ```VerbClassificationAdv``` model
https://github.com/uvavision/Balanced-Datasets-Are-Not-Enough/blob/51d66c54a81ad88a3ffd6a15d3807be3d5263f01/verb_classification/adv/adv_model.py#L9

The returned value from the ```forward``` function is 
https://github.com/uvavision/Balanced-Datasets-Are-Not-Enough/blob/51d66c54a81ad88a3ffd6a15d3807be3d5263f01/verb_classification/adv/adv_model.py#L188
which are main task predictions and adv predictions, respectively.

So, it seems that the extracted ```potentials```  are actually adv predictions ( 2d ) rather the model predictions (211d ).

**Comment by tianlu-wang** [comment]
Hi Xudong and Aili,

Thanks for pointing this out! I have fixed this bug. Please checkout this [commit](https://github.com/uvavision/Balanced-Datasets-Are-Not-Enough/commit/023c4ff42e7002b648752231c30a292ed0b20229)
